import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Pc Tricomputo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img src="" alt="" />
          <a href="/">Home</a>
          <a href="/events">Productos</a>
          <a href="/about-us">About-us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <div>
          <img />
          <h2>Nuestros Productos </h2>
        </div>

       
      </main>
      <footer className={styles.footer}>
        <p>© 2023 PC Tricomputo - Todos los derechos reservados. 

        </p>

      </footer>
    </>
  )
}
